import PageHero from '@/components/heros/PageHero'
import NewsLetter from '@/components/NewsLetter'
import Services from '@/components/Services'
import MembersCounter from '@/components/MembersCounter'
import Pricing from '@/components/Pricing'
export const metadata = {
  title: 'Komek Me Services',
  description: 'Generated by StaticMania',
}
export default function ServicePage() {
  return (
    <>
      <PageHero
        subtitle="НАШИ УСЛУГИ"
        title="Лучшие компании мира <br> доверяют нам"
        paragraph="Мы предоставляем полный спектр IT-услуг для развития и оптимизации вашего бизнеса"
      />
      <Services sectionDetails={false} />
      <MembersCounter />
      <Pricing spacing={'pt-150 max-md:pt-20'} />
      <NewsLetter />
    </>
  )
}
